[parameters]
initial_mini_weight = 0.5
tolerance_percent = 10.0
stability_threshold = 0.02
max_batch_pieces = 4
initial_single_pieces = 5
force_pieces = 5
target_pieces = 100
decimal_places = 2

[ui]
splitter_sizes = [ 140, 199,]

[serial]
port = "COM1"
baud_rate = 9600
